### ISSUE TITLE
Kleine UI dingetjes

### ISSUE THREAD

**Issue by krijnhoetmer** [kasszz/minor-web-development#11]
Je demo voelt super polished aan, waardoor dit extra opvalt:

- vote-knop is wat ielig, vergeleken bij de rest
- witruimte rondom radio buttons mag wel iets groter
- ik mis een pointer bij de 4 options (opinionated ;)

**Comment by kasszz** [comment]
Ben ik het helemaal mee eens, het was ook echt een tijd issue dat ik dat niet heb gedaan.
