### ISSUE TITLE
Vertical Centering

### ISSUE THREAD

**Issue by MicheleNL** [kasszz/minor-web-development#5]
Ik kan je vertical centering opdracht niet vinden, misschien kijk ik er overheen? Mocht ik hem gemist hebben, geef dan nog even aan waar ie zit, dan kijk ik er naar.

**Comment by kasszz** [comment]
Als u op profile picture drukt :) daar staat ook opdracht #6

**Comment by MicheleNL** [comment]
Ha! Gezien, thanks. Eerder over het hoofd gezien omdat je layover bij mij niet op mijn scherm past, hij is wat aan de hoge kant. Wellicht kun je hier nog even naar kijken.
